# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 23:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargoPlane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Name of plane(eg. YH12)', max_length=200)),
                ('description', models.TextField(help_text='Enter a brief description', max_length=1000)),
                ('terminal', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(1)])),
                ('size', models.CharField(choices=[('2', '2'), ('4', '4'), ('6', '6')], default='2', max_length=6)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Name of plane(eg. YH12)', max_length=200)),
                ('description', models.TextField(help_text='Enter a brief description', max_length=1000)),
                ('size', models.CharField(choices=[('2', '2'), ('4', '4'), ('6', '6')], default='2', max_length=6)),
                ('plane_type', models.CharField(choices=[('Domestic', 'Domestic'), ('International', 'International'), ('Cargo', 'Cargo')], default='Domestic', max_length=6)),
                ('terminal', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(1)])),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternationalPlane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Name of plane(eg. YH12)', max_length=200)),
                ('description', models.TextField(help_text='Enter a brief description', max_length=1000)),
                ('terminal', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(1)])),
                ('size', models.CharField(choices=[('2', '2'), ('4', '4'), ('6', '6')], default='2', max_length=6)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalPlane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Name of plane(eg. YH12)', max_length=200)),
                ('description', models.TextField(help_text='Enter a brief description', max_length=1000)),
                ('terminal', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(1)])),
                ('size', models.CharField(choices=[('2', '2'), ('4', '4'), ('6', '6')], default='2', max_length=6)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='localplane',
            unique_together=set([('terminal', 'id')]),
        ),
        migrations.AlterUniqueTogether(
            name='internationalplane',
            unique_together=set([('terminal', 'id')]),
        ),
        migrations.AlterUniqueTogether(
            name='emergency',
            unique_together=set([('terminal', 'id')]),
        ),
        migrations.AlterUniqueTogether(
            name='cargoplane',
            unique_together=set([('terminal', 'id')]),
        ),
    ]
