# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 23:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='terminal',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
