# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170708_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='plane_type',
            field=models.CharField(choices=[('Domestic', 'Domestic'), ('International', 'International'), ('Cargo', 'Cargo')], default='Domestic', max_length=15),
        ),
    ]
